# Generated by Django 2.1.2 on 2018-10-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SmallIntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('tamano', models.FloatField()),
                ('peso', models.FloatField()),
                ('color', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_rescate', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Rescatado', 'Rescatado'), ('Disponibilidad', 'Disponibilidad'), ('Adoptado', 'Adoptado')], max_length=30)),
            ],
        ),
    ]
